#ifdef SEVEN_SEG_COMMON_H_
#define SEVEN_SEG_COMMON_H_

#define SEVEN_SEG_CONFIG_DIGITS_MAX 5

#define SEVEN_SEG_RES_OK		0
#define SEVEN_SEG_RES_INV_ARG	-1
#define SEVEN_SEG_RES_ERR		-2

#define DIGIT_SEG_A	0x01
#define DIGIT_SEG_B	0x02
#define DIGIT_SEG_C	0x04
#define DIGIT_SEG_D	0x08
#define DIGIT_SEG_E	0x10
#define DIGIT_SEG_F	0x20
#define DIGIT_SEG_G	0x40
#define DIGIT_SEG_DOT	0x80

#define DIGIT_0 ( DIGIT_SEG_A | DIGIT_SEG_B | DIGIT_SEG_C | DIGIT_SEG_D |DIGIT_SEG_E | DIGIT_SEG_F )
#define DIGIT_1 ( DIGIT_SEG_B | DIGIT_SEG_C )
#define DIGIT_2 ( DIGIT_SEG_A | DIGIT_SEG_B | DIGIT_SEG_D | DIGIT_SEG_E | DIGIT_SEG_G )
#define DIGIT_3 ( DIGIT_SEG_A | DIGIT_SEG_B | DIGIT_SEG_C | DIGIT_SEG_D | DIGIT_SEG_G )
#define DIGIT_4 ( DIGIT_SEG_B | DIGIT_SEG_C | DIGIT_SEG_F | DIGIT_SEG_G )
#define DIGIT_5 ( DIGIT_SEG_A | DIGIT_SEG_C | DIGIT_SEG_D | DIGIT_SEG_F, DIGIT_SEG_G )
#define DIGIT_6 ( DIGIT_SEG_A | DIGIT_SEG_C | DIGIT_SEG_D | DIGIT_SEG_E |DIGIT_SEG_F | DIGIT_SEG_G )
#define DIGIT_7 ( DIGIT_SEG_A | DIGIT_SEG_B | DIGIT_SEG_C )
#define DIGIT_8 ( DIGIT_SEG_A | DIGIT_SEG_B | DIGIT_SEG_C | DIGIT_SEG_D |DIGIT_SEG_E | DIGIT_SEG_F | DIGIT_SEG_G )
#define DIGIT_9 ( DIGIT_SEG_A | DIGIT_SEG_B | DIGIT_SEG_C | DIGIT_SEG_F | DIGIT_SEG_G )
#define DIGIT_A ( DIGIT_SEG_A | DIGIT_SEG_B | DIGIT_SEG_C | DIGIT_SEG_E | DIGIT_SEG_F | DIGIT_SEG_G )
#define DIGIT_B ( DIGIT_SEG_C | DIGIT_SEG_D |DIGIT_SEG_E | DIGIT_SEG_F | DIGIT_SEG_G )
#define DIGIT_C ( DIGIT_SEG_A | DIGIT_SEG_D | DIGIT_SEG_E | DIGIT_SEG_F )
#define DIGIT_D ( DIGIT_SEG_B | DIGIT_SEG_C | DIGIT_SEG_D | DIGIT_SEG_E | DIGIT_SEG_G)
#define DIGIT_E ( DIGIT_SEG_A | DIGIT_SEG_D |DIGIT_SEG_E | DIGIT_SEG_F | DIGIT_SEG_G )
#define DIGIT_F ( DIGIT_SEG_A | DIGIT_SEG_E | DIGIT_SEG_F | DIGIT_SEG_G )

#endif