/*
 * composer_config.h
 *
 *  Created on: 1 okt. 2018
 *      Author: Dorus
 */

#ifndef COMPOSER_CONFIG_H_
#define COMPOSER_CONFIG_H_

/* Driver configuration. */
#define COMPOSER_CONFIG_ENABLE_MODULE_RGB_LED	1
#define COMPOSER_CONFIG_ENABLE_MODULE_SEVEN_SEG	1
#define COMPOSER_CONFIG_ENABLE_MODULE_TIME		1
#define COMPOSER_CONFIG_ENABLE_MODULE_PUMP		1
#define COMPOSER_CONFIG_ENABLE_MODULE_STORAGE	1
#define COMPOSER_CONFIG_ENABLE_MODULE_BUTTON	1

/* Sys task configuration. */
#define COMPOSER_CONFIG_ENABLE_MODULE_SYSTEM_MANAGER			1
#define COMPOSER_CONFIG_ENABLE_MODULE_IRRIGATION_CONTROLLER		1
#define COMPOSER_CONFIG_ENABLE_MODULE_SCHEDULE_MANAGER			1
#define COMPOSER_CONFIG_ENABLE_MODULE_UI_CONTROLLER				1

#endif /* COMPOSER_CONFIG_H_ */
