/*
 * composer_config.h
 *
 *  Created on: 1 okt. 2018
 *      Author: Dorus
 */

#ifndef COMPOSER_CONFIG_H_
#define COMPOSER_CONFIG_H_

/* Driver configuration. */
#define COMPOSER_CONFIG_ENABLE_MODULE_RGBLED	0
#define COMPOSER_CONFIG_ENABLE_MODULE_SEVENSEG	0
#define COMPOSER_CONFIG_ENABLE_MODULE_TIME		0
#define COMPOSER_CONFIG_ENABLE_MODULE_PUMP		0
#define COMPOSER_CONFIG_ENABLE_MODULE_STORAGE	0
#define COMPOSER_CONFIG_ENABLE_MODULE_BUTTON	0

/* Sys task configuration. */
#define COMPOSER_CONFIG_ENABLE_MODULE_IRRIGATIONCONTROLLER	0
#define COMPOSER_CONFIG_ENABLE_MODULE_SCHEDULEMANAGER		0
#define COMPOSER_CONFIG_ENABLE_MODULE_UICONTROLLER			0

#endif /* COMPOSER_CONFIG_H_ */
